version: "3"
services:
  node01:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8080"
    volumes:
      - ../data/node01:/app/data
      - ../data/node01:/app/Models

  # node02:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - ../data/node02:/app/data
  #     - ../data/node02:/app/Models