version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8081:8080"
    volumes:
      - ../data:/app/data
      - ../data:/app/Models

  # newClinet:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - ../data/node02:/app/data
  #     - ../data/node02:/app/Models